name: Publishing Process

on:
  push:
    branches: [main]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Installing Dependencies
        working-directory: ./
        run: npm ci

      - name: Performing Unit Testing
        working-directory: ./
        run: npm run test:jest-ci

      - name: Creating Production Build
        working-directory: ./
        run: npm run build

      #- name: Publish to GitHub Packages
      #  run: npm publish --registry=https://npm.pkg.github.com/@imraan-hendricks
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
